"""status-row-pty.py — status row above the footer frame under a real pty.

Child argv is `node $PROBE_JS` (generated by status-row.mjs): installs
a HostFooter on a 14x80 pty (pinned: frame 13, model 14), attaches a
KindStatus, runs one 1-echo turn (~350ms of ticks), stops, prints DONE.
The pty merges stdout+stderr, so newline accounting is 5 total: 1 open
scroll + 3 commit parks + DONE. Prints one line for the drill:
  PARSED status=S frame=F model=M ticks=N newlines=K summary=yes/no rows=R,...
status/frame/model are the distinct CUP rows carrying status text /
FRAME-1 / MODEL-1; ticks counts row-S paints carrying a spinner glyph;
summary checks the `2K done` commit on row S; rows lists every CUP row
touched after install.
"""
import fcntl
import os
import pty
import re
import select
import struct
import sys
import termios
import time

ROWS, COLS = 14, 80
TIMEOUT = 30.0
SPINNERS = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏◐◓◑◒"

pid, fd = pty.fork()
if pid == 0:
    os.environ["TERM"] = os.environ.get("TERM", "xterm-256color")
    os.execvp("node", ["node", os.environ["PROBE_JS"]])
fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", ROWS, COLS, 0, 0))
os.set_blocking(fd, False)

out = b""
t0 = time.monotonic()
alive = True
while time.monotonic() - t0 < TIMEOUT:
    r, _, _ = select.select([fd], [], [], 0.1)
    if r:
        try:
            chunk = os.read(fd, 65536)
        except OSError:
            break
        if not chunk:
            break
        out += chunk
    try:
        wpid, _ = os.waitpid(pid, os.WNOHANG)
        if wpid != 0:
            time.sleep(0.2)
            try:
                while True:
                    chunk = os.read(fd, 65536)
                    if not chunk:
                        break
                    out += chunk
            except OSError:
                pass
            break
    except ChildProcessError:
        break

text = out.decode("utf-8", "replace")
# Split the stream into (cup_row, body) segments: each CUP starts one.
segs = []
for m in re.finditer(r"\x1b\[(\d+);1H", text):
    segs.append((int(m.group(1)), m.start()))
rows_touched = sorted({r for (r, _) in segs})


def body_after(idx):
    start = segs[idx][1]
    end = segs[idx + 1][1] if idx + 1 < len(segs) else len(text)
    return text[start:end]


status_rows = [r for (i, (r, _)) in enumerate(segs) if any(g in body_after(i) for g in SPINNERS)]
frame_rows = [r for (i, (r, _)) in enumerate(segs) if "FRAME-1" in body_after(i)]
model_rows = [r for (i, (r, _)) in enumerate(segs) if "MODEL-1" in body_after(i)]
# Install paints FRAME-1/MODEL-1 first at the pinned rows; the open
# repaints them shifted — the LAST rows carrying each win.
status = status_rows[-1] if status_rows else -1
frame = frame_rows[-1] if frame_rows else -1
model = model_rows[-1] if model_rows else -1
ticks = sum(1 for (i, (r, _)) in enumerate(segs) if r == status and any(g in body_after(i) for g in SPINNERS))
newlines = text.count("\n")
summary = "yes" if re.search(r"\x1b\[" + str(status) + r";1H\x1b\[2K.*done", text) else "no"
print(f"PARSED status={status} frame={frame} model={model} ticks={ticks} newlines={newlines} summary={summary} rows={','.join(map(str, rows_touched))}")
